### ISSUE TITLE
Node 22 LTS breaks integration tests 

### ISSUE THREAD

**Issue by fatso83** [sinonjs/fake-timers#518]
The latest commits fail on Node 22. They started failing on Dec 5, but it was not related to any code changes. I verified the tests failed on the code preceding that if using Node 22, with no other changes. The tests started failing due to [Node 22 landing in the LTS version on October 29](https://nodejs.org/en/blog/release/v22.11.0). Since we had no commits after Oct 29 until December, nothing was triggered. 

**How to reproduce**
Check out `main` locally, choose to use Node 22 and run the tests. This is what I did (relying on [ASDF](https://asdf-vm.com/) and .tool-versions):
```
fake-timers on  main [106508?] is 📦 v13.0.5 via  v20.9.0 on ☁️  (eu-north-1) on ☁️
❯ asdf local nodejs 20.9.0

fake-timers on  main [106508?] is 📦 v13.0.5 via  v20.9.0 on ☁️  (eu-north-1) on ☁️
❯ npx mocha --timeout 200  integration-test/  -R dot --check-leaks


  ....

  4 passing (42ms)

❯ asdf local nodejs 22.12.0

fake-timers on  main [106510?] is 📦 v13.0.5 via  v22.12.0 on ☁️  (eu-north-1) on ☁️
❯ npx mocha --timeout 200  integration-test/  -R dot --check-leaks
(node:12244) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)


  ...!!

  3 passing (38ms)
  2 failing

  1) globally configured browser objects
       correctly instantiates and tears down:
     TypeError: Cannot set property navigator of #<Object> which has only a getter
      at setUpGlobal (integration-test/fake-clock-integration-test.js:91:26)
      at Context.<anonymous> (integration-test/fake-clock-integration-test.js:120:9)
      at process.processImmediate (node:internal/timers:491:21)

  2) globally configured browser objects
       correctly instantiates and tears down:
     Error: global leak(s) detected: 'window', 'document'
      at Runner.emit (node:events:536:35)
      at process.processImmediate (node:internal/timers:491:21)

```

**Comment by fatso83** [comment]
This is due to the introduction of a partial implementation of the [Navigator API in Node 21](https://nodejs.org/api/globals.html#navigator_1). If listing through the keys we get this:
```
navigator Navigator {}
hardwareConcurrency 12
language no-NO
languages [ 'no-NO' ]
userAgent Node.js/22
platform MacIntel
```

I'll preserve this, delete the prop and recreate it in the tests.
